---

- name: Deploy systemd rest-server service units
  template:
    src: systemd.service.j2
    dest: "/etc/systemd/system/rest-server-{{ item.path | hash('sha1') | truncate(6, True, '') }}.service"
  with_items: '{{ restic_rest_repos }}'

- name: Enable and start systemd rest-server service units
  systemd:
    state: started
    enabled: yes
    daemon_reload: yes
    name: "rest-server-{{ item.path | hash('sha1') | truncate(6, True, '') }}.service"
  with_items: '{{ restic_rest_repos }}'
  when: restic_rest_service_enable

- name: Deploy systemd rest-server.target
  template:
    src: systemd.target.j2
    dest: "/etc/systemd/system/rest-server.target"
